# Generated by Django 4.2.24 on 2025-09-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(db_index=True, max_length=100)),
                ('frameType', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('atk', models.IntegerField(blank=True, db_index=True, null=True)),
                ('def_stat', models.IntegerField(blank=True, db_index=True, null=True)),
                ('level', models.IntegerField(blank=True, db_index=True, null=True)),
                ('race', models.CharField(db_index=True, max_length=100)),
                ('attribute', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(db_index=True, max_length=255)),
                ('set_code', models.CharField(db_index=True, max_length=50)),
                ('set_rarity', models.CharField(max_length=100)),
                ('set_rarity_code', models.CharField(max_length=20)),
                ('set_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sets', to='YugiCall.card')),
            ],
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['name'], name='YugiCall_ca_name_e8d4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['type'], name='YugiCall_ca_type_07b673_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['race'], name='YugiCall_ca_race_3db1c4_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['attribute'], name='YugiCall_ca_attribu_4c38d4_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['atk'], name='YugiCall_ca_atk_66594a_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['def_stat'], name='YugiCall_ca_def_sta_7ce93e_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['level'], name='YugiCall_ca_level_4b1bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='cardset',
            index=models.Index(fields=['set_name'], name='YugiCall_ca_set_nam_f72c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='cardset',
            index=models.Index(fields=['set_code'], name='YugiCall_ca_set_cod_a5bbc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardset',
            constraint=models.UniqueConstraint(fields=('card', 'set_code'), name='uniq_card_setcode'),
        ),
    ]
