# Generated by Django 5.2.5 on 2025-09-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YugiCall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardEN',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(db_index=True, max_length=100)),
                ('frameType', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('atk', models.IntegerField(blank=True, db_index=True, null=True)),
                ('def_stat', models.IntegerField(blank=True, db_index=True, null=True)),
                ('level', models.IntegerField(blank=True, db_index=True, null=True)),
                ('race', models.CharField(db_index=True, max_length=100)),
                ('attribute', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Card (EN)',
                'verbose_name_plural': 'Cards (EN)',
                'indexes': [models.Index(fields=['name'], name='YugiCall_ca_name_696ea0_idx'), models.Index(fields=['type'], name='YugiCall_ca_type_a1b546_idx'), models.Index(fields=['race'], name='YugiCall_ca_race_d73954_idx'), models.Index(fields=['attribute'], name='YugiCall_ca_attribu_80de26_idx'), models.Index(fields=['atk'], name='YugiCall_ca_atk_6c2c86_idx'), models.Index(fields=['def_stat'], name='YugiCall_ca_def_sta_504ed5_idx'), models.Index(fields=['level'], name='YugiCall_ca_level_22b9bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CardSetEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(db_index=True, max_length=255)),
                ('set_code', models.CharField(db_index=True, max_length=50)),
                ('set_rarity', models.CharField(max_length=100)),
                ('set_rarity_code', models.CharField(max_length=20)),
                ('set_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sets', to='YugiCall.carden')),
            ],
            options={
                'verbose_name': 'Card Set (EN)',
                'verbose_name_plural': 'Card Sets (EN)',
                'indexes': [models.Index(fields=['set_name'], name='YugiCall_ca_set_nam_146406_idx'), models.Index(fields=['set_code'], name='YugiCall_ca_set_cod_5465e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('card', 'set_code'), name='uniq_card_en_setcode')],
            },
        ),
    ]
